config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
              controllers: {
                sessions: 'users/sessions',
                registrations: 'users/registrations'
              }
get '/member-data', to: 'members#show'
  resources :users, only: [:index, :show] do 
    resources :posts, only: [:index, :show]
  end
  get '/create_post', to: 'posts#create_post'
  post '/create', to: 'posts#create'
  post '/users/:user_id/posts/:post_id/create', to: 'comments#create'
  post '/like/create', to: 'likes#create'
  root 'users#index'


  namespace :api do
      resources :posts, only: %i[index show new create destroy] do
        resources :comments, only: %i[index new create destroy]
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :jwt_authenticatable, jwt_revocation_strategy: JwtDenylist
  validates :name, :bio, :email, presence: true
  validates :posts_counter, numericality: { greater_than_or_equal_to: 0 }

  has_many :comments, dependent: :destroy, foreign_key: 'user_id'
  has_many :likes, dependent: :destroy, foreign_key: 'user_id'
  has_many :posts, dependent: :destroy, foreign_key: 'user_id'

  def my_recent_posts
    posts.limit(3).order(created_at: :desc)
  end
end

app/controllers/users/registration_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  respond_to :json

  private

  def respond_with(resource, _opts = {})
    register_success && return if resource.persisted?

    register_failed
  end

  def register_success
    render json: { message: 'Sucessfully signed UP' }
  end

  def register_failed
    render json: { message: 'Something went wrong.' }
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  respond_to :json
  skip_before_action :verify_authenticity_token, only: [:create]

  private

  def respond_with(_resource, _opts = {})
    render json: { message: 'You are logged in.' }, status: :ok
  end

  def respond_to_on_destroy
    log_out_success && return if current_user

    log_out_failure
  end

  def log_out_success
    render json: { message: 'You are logged out.' }, status: :ok
  end

  def log_out_failure
    render json: { message: 'Hmm nothing happened.' }, status: :unauthorized
  end
end

app/controllers/users_controller.rb
# Controller for users
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all.order('id')
  end

  def show
    @user = User.find(params[:id])
    @user_posts = @user.recent_posts
    @comments = Comment.all
  end
end

app/helpers/users_helper.rb
# Users helper
module UsersHelper
end

app/views/users/_user.html.erb
<article class="user">
    <img src="<%= user.photo %>" class="users-image">
    <div class="users-info">
      <%= link_to user_path(user.id) do %>
        <span class="username"><%= user.name %></span>
      <% end %>
      <div class="user-posts">Number of posts: <span class="post-count"><%= user.posts_counter ? user.posts_counter : 0 %></span></div>
    </div>
</article>

app/views/users/index.html.erb
<%= render partial: 'shared/header' %>
<ul>
  <% @users.each do |user| %>

     <%= render partial: 'user', locals: {user: user} %>
   
  <% end %>
</ul>

app/views/users/show.html.erb
<%= render partial: 'shared/header' %>

<%= render partial: 'user', locals: {user: @user} %>
<div class="bio">
<h2>Bio</h2>
<p>
  <%= @user.bio %>
</p>
</div>


<ul class="posts wo-comments">
  <% @user_posts.each do |post| %>
    <%= render partial:'posts/post', locals:{post: post, users: @users, comments: @comments}%>
  <% end %>
</ul>

<%= link_to "See all post", user_posts_path(@user.id) %>