config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
              controllers: {
                sessions: 'users/sessions',
                registrations: 'users/registrations'
              }
get '/member-data', to: 'members#show'
  resources :users, only: [:index, :show] do 
    resources :posts, only: [:index, :show]
  end
  get '/create_post', to: 'posts#create_post'
  post '/create', to: 'posts#create'
  post '/users/:user_id/posts/:post_id/create', to: 'comments#create'
  post '/like/create', to: 'likes#create'
  root 'users#index'


  namespace :api do
      resources :posts, only: %i[index show new create destroy] do
        resources :comments, only: %i[index new create destroy]
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', counter_cache: :posts_counter
  has_many :likes, dependent: :destroy, foreign_key: 'post_id'
  has_many :comments, dependent: :destroy, foreign_key: 'post_id'

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def last_comments
    comments.last(5)
  end

  private

  def update_post_counter
    author.update!(:posts_counter)
  end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    @posts = Post.all
    render json: @posts
  end
end

app/controllers/posts_controller.rb
#  Controller for posts
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @user = User.find(params[:user_id])
    @users = User.all
    @user_posts = Post.includes(:author).where(author: @user)
    @comments = Comment.all
  end

  def show
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id])
    @comments = @post.comments.all.order(created_at: :desc)
    @users = User.all
    @likes = @post.likes.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new post_params
    @post.author = current_user
    if @post.save

      redirect_to user_posts_path, notice: 'Post added successfully!'
    else
      flash[:alert] = @post.errors.first.full_message
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to user_posts_path, alert: 'Post deleted successfully!'
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/views/posts/_post.html.erb
 
<li class="post">
  <%= link_to user_post_path(post.author.id, post.id) do %>
      <h3><%= post.title %></h3>
        <% end %>
      <p><%= post.text %></p>

      <div class="stats">
        <div>Comments: <%= post.comments_counter ? post.comments_counter : 0 %></div>
        <div>Likes: <%= post.likes_counter ? post.likes_counter : 0 %></div>
      </div>

      <ul class="comments">
        <% filtered_comments = comments.select{|a| a.post_id == post.id } %>
        <% filtered_comments.each do |comment| %>
              <li>
                <%= comment.author.name %>
                <%= comment.text %>
              </li>
            
        <% end %>
      </ul>
  </li>

app/views/posts/index.html.erb
<%= render partial: 'shared/header' %>

<%= render partial:'users/user', locals: {user: @user} %>
<p>
  <%= @user.bio %>
</p>

<ul>
  <% @user_posts.each do |post| %>
    <%= render partial:'post', locals:{post: post, users: @users, comments: @comments} %>
  <% end %>
</ul>
<% unless @user_posts.size == 0 %>
  <button>Pagination</button>
<% end %>

app/views/posts/new.html.erb
<%= form_with model: Post.new, :url => {:action => :create, :controller => :posts}, class:"post-form" do |form| %>
  <h1>New post</h1>
  <div>
    <%= form.label :title%>
    <%= form.text_field :title %>
    
  <div>
  <div>
    <%= form.label :text %>
    <%= form.text_area :text %>
  <div>

  <%= form.submit "Save post", class:"btn" %>
  <% end %>

app/views/posts/show.html.erb
<%= render partial: 'shared/header' %>
<div class="post-header">
  <h2><%= @post.title %></h2>
  by<span><%= @user.name %> </span>
  <div class="stats">
    Comments: <%= @comments.count %>
    Likes: <%= @likes.count %>
  </div>
</div>
 <p>
  <%= @post.text %>
</p>
<div class="buttons">
  <%= link_to 'Add comment', user_post_path(params[:user_id], params[:id])+'/comments/new', class:'btn' %>
  <%= button_to 'Like', likes_path, params:{like:{post_id:@post.id}}, method: :post, class:'btn' %>
  <% if can? :destroy, @post %>
    <%= link_to 'Delete post', { :controller=>:posts,:action=>:destroy, :id=>params[:id] }, :method=>:delete, class:'btn btn-danger' %>
  <% end %>
</div>
<ul class="comments">
  <% @comments.each do |comment| %>
    <li class="comment">
      <%= comment.author.name %>:
      <%= comment.text %>
      <% if can? :destroy, comment %>
       <%= link_to 'Delete Comment',  user_post_comment_path(params[:user_id], @post, comment),   method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger' %>
      <% end %>

    </li>

  <% end %>
</ul>